first commit
mkaanilhan/IT537-2024-Assignment-1 pull request #19
Opened 2024-06-30 09:15 UTC by barankrkrt

I tried but needs improvement for desired page.

2024-07-03 08:13 UTC, mkaanilhan requested changes
tabloda satırlar arasında gezerken hover effect yok -5
display: grid kullanmamışsın -5
iconlar gözükmüyor, bir kaç buton gereğinden fazla kaymış -5

85

2024-07-03 09:50 UTC, barankrkrt commented
Hocam fazla gitmiş puanım :) Düzeltme yapabiliyor muyuz 5 - 10 puanlık.

On Wed, Jul 3, 2024 at 11:13 AM mkaanilhan ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> tabloda satırlar arasında gezerken hover effect yok -5
> display: grid kullanmamışsın -5
> iconlar gözükmüyor, bir kaç buton gereğinden fazla kaymış -5
>
> 85
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mkaanilhan/IT537-2024-Assignment-1/pull/19#pullrequestreview-2155767355>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5WPOQ6RWUV6DGLZRMA3WUTZKOXDXAVCNFSM6AAAAABKD56ZWGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNJVG43DOMZVGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-05 15:15 UTC, mkaanilhan approved these changes

2024-07-05 15:15 UTC, mkaanilhan commented
100

2024-08-06 06:36 UTC, closed without merging