first commit
mkaanilhan/IT537-2024-Assignment-1 pull request #20
Opened 2024-06-30 11:46 UTC by doganalperr

Merhaba,

Doğan Can Alper

Saygılarımla.

2024-07-03 08:29 UTC, mkaanilhan requested changes
tablo eksik -10
layout yanlış -10
languages kısmına ait color bar eksik -5

75

2024-07-07 19:04 UTC, mkaanilhan requested changes
layout hatalı,tablo ile diğer kısmın yeri değişmeli. Demo video'ya bakabilirsin.
tablo'da satırları gezinirken row effect yok -5

85

2024-07-08 06:05 UTC, mkaanilhan commented
100

2024-07-08 06:09 UTC, doganalperr commented
Teşekkürler Hocam.

8 Tem 2024 Pzt 09:05 tarihinde mkaanilhan ***@***.***> şunu
yazdı:

> 100
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mkaanilhan/IT537-2024-Assignment-1/pull/20#issuecomment-2213098373>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BHEOZZLJJQDX63FTURGCVRDZLIT3RAVCNFSM6AAAAABKEBCZBOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMJTGA4TQMZXGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-06 06:36 UTC, closed without merging